import { useState } from "react";
import { Bell, Bot, Calendar, ChevronRight, Database, Eye, EyeOff, FileText, HardDrive, KeyRound, MemoryStick, Monitor, Save, Shield, SlidersHorizontal } from "lucide-react";
import { Badge, Button, Card } from "@keen/ui";

const sections = [
  ["General", SlidersHorizontal], ["Models", Bot], ["Embeddings", Database], ["Knowledge", HardDrive], ["Memory", MemoryStick],
  ["Privacy", Shield], ["Calendar", Calendar], ["Notifications", Bell], ["Appearance", Monitor], ["Advanced", SlidersHorizontal], ["Open Source Notices", FileText],
] as const;

export function SettingsPage() {
  const [section, setSection] = useState("Models");
  const [provider, setProvider] = useState("OpenAI-compatible");
  const [keySet, setKeySet] = useState(false);
  const [showKey, setShowKey] = useState(false);
  const [endpoint, setEndpoint] = useState("https://api.openai.com/v1");
  return (
    <div className="settings-page"><aside><h1>Settings</h1>{sections.map(([label, Icon]) => <button className={section === label ? "active" : ""} key={label} onClick={() => setSection(label)}><Icon size={15} /><span>{label}</span><ChevronRight size={13} /></button>)}</aside>
      <main><header><div><small>Settings · demo mode</small><h2>{section}</h2></div><Button className="primary" disabled><Save size={14} />Saving unavailable</Button></header>
        <div className="demo-disclosure"><Badge tone="warning">Settings preview</Badge><span>Controls on this page are not applied or persisted. Provider secrets are never saved; Keychain and capability adapters are not connected.</span></div>
        {section === "Models" ? <div className="settings-content"><Card className="settings-card"><div className="settings-card-head"><div><Bot size={18} /><span><strong>Chat model</strong><small>Provider configuration preview; not persisted yet.</small></span></div><Badge tone="warning">Not configured</Badge></div><div className="settings-form"><div className="field"><label>Provider</label><select value={provider} onChange={(e) => setProvider(e.target.value)}><option>OpenAI-compatible</option><option>Anthropic-compatible</option><option>Gemini-compatible</option><option>Ollama</option><option>LM Studio</option><option>Custom endpoint</option></select></div><div className="field"><label>Model</label><select><option>gpt-4.1-mini</option><option>gpt-4.1</option><option>Custom model ID</option></select></div><div className="field full"><label>Endpoint</label><input value={endpoint} onChange={(e) => setEndpoint(e.target.value)} /></div><div className="field full"><label>API key</label><div className="secret-field"><KeyRound size={15} /><input type={showKey ? "text" : "password"} placeholder={keySet ? "Unsaved key entered" : "Enter API key (not saved)"} onChange={(e) => setKeySet(Boolean(e.target.value))} /><button aria-label={showKey ? "Hide key" : "Show key"} onClick={() => setShowKey(!showKey)}>{showKey ? <EyeOff size={15} /> : <Eye size={15} />}</button></div><small>Not saved in this build. macOS Keychain integration is pending.</small></div></div><div className="settings-card-footer"><Button disabled>Test connection unavailable</Button><span>Sidecar and provider adapters are not connected.</span></div></Card>
          <Card className="settings-card"><div className="settings-card-head"><div><SlidersHorizontal size={18} /><span><strong>Generation defaults preview</strong><small>Not applied to conversations in this build.</small></span></div></div><div className="setting-row"><span><strong>Stream responses</strong><small>Preview only</small></span><label className="switch"><input type="checkbox" defaultChecked disabled /><i /></label></div><div className="setting-row"><span><strong>Show agent trace</strong><small>Preview only</small></span><label className="switch"><input type="checkbox" disabled /><i /></label></div><div className="setting-row"><span><strong>Default model routing</strong><small>Preview only</small></span><label className="switch"><input type="checkbox" defaultChecked disabled /><i /></label></div></Card>
        </div> : section === "Open Source Notices" ? <div className="settings-content"><Card className="settings-card"><div className="settings-card-head"><div><FileText size={18} /><span><strong>Open source software preview</strong><small>Illustrative subset only. The bundled THIRD_PARTY_NOTICES.md is authoritative and still records known reconciliation gaps.</small></span></div></div>{["React · MIT", "Tauri · Apache-2.0 / MIT", "Lucide · ISC", "Zustand · MIT", "TanStack Query · MIT"].map((item) => <div className="notice-row" key={item}><span>{item}</span><Button disabled>Viewer unavailable</Button></div>)}</Card></div> : <div className="settings-content"><Card className="settings-card placeholder-settings"><div className="settings-card-head"><div>{section === "Privacy" ? <Shield size={18} /> : <SlidersHorizontal size={18} />}<span><strong>{section} preferences preview</strong><small>This capability is not connected.</small></span></div></div><div className="setting-row"><span><strong>Enable {section.toLowerCase()} features</strong><small>Preview only; no change is stored or applied.</small></span><label className="switch"><input type="checkbox" defaultChecked disabled /><i /></label></div><div className="setting-row"><span><strong>Ask before external changes</strong><small>No external writer exists in this build.</small></span><label className="switch"><input type="checkbox" defaultChecked disabled /><i /></label></div></Card></div>}
      </main>
    </div>
  );
}
